# ============================================================================
# Impulse Bootstrap Payload Manifest Generator
# Generates installer include data and a publish manifest for hosted payloads.
# ============================================================================

param(
    [string]$BaseUrl = $env:WHISPER_BOOTSTRAP_BASE_URL,
    [string]$Version
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Resolve-Path (Join-Path $ScriptDir "..\..")
$DistRoot = Join-Path $ProjectRoot "dist\Impulse"
$IncludePath = Join-Path $ScriptDir "bootstrap_payload.iss.inc"

function Get-AppVersion {
    $configPath = Join-Path $ProjectRoot "src\whisper_local\config.py"
    $match = Select-String -Path $configPath -Pattern 'APP_VERSION\s*=\s*"([^"]+)"' -AllMatches | Select-Object -First 1
    if ($match -and $match.Matches.Count -gt 0) {
        return $match.Matches[0].Groups[1].Value
    }

    throw "Unable to determine application version from src\whisper_local\config.py"
}

if (-not $Version) {
    $Version = Get-AppVersion
}

if ([string]::IsNullOrWhiteSpace($BaseUrl)) {
    throw "Bootstrap payload base URL is required. Set WHISPER_BOOTSTRAP_BASE_URL or pass -BaseUrl."
}

$NormalizedBaseUrl = $BaseUrl.TrimEnd('/')

$requiredPayloadRelativePaths = @(
    "_internal\ggml-base.dll",
    "_internal\ggml.dll",
    "_internal\models\ggml-base.en.bin",
    "_internal\whisper-cli.exe",
    "_internal\whisper.dll"
)

foreach ($relativePath in $requiredPayloadRelativePaths) {
    $sourcePath = Join-Path $DistRoot $relativePath
    if (-not (Test-Path $sourcePath)) {
        throw "Missing required bootstrap payload file: $sourcePath"
    }
}

# whisper.cpp now publishes CPU DLLs with architecture suffixes such as
# ggml-cpu-haswell.dll. Discover the files produced by the current build so
# the bootstrap payload cannot drift from the packaged runtime again.
$runtimeRoot = Join-Path $DistRoot "_internal"
$cpuDlls = @(Get-ChildItem $runtimeRoot -Filter "ggml-cpu*.dll" -File -ErrorAction SilentlyContinue)
if ($cpuDlls.Count -eq 0) {
    throw "Missing required bootstrap CPU runtime: $runtimeRoot\ggml-cpu*.dll"
}

$optionalRuntimeFiles = @(
    Get-ChildItem $runtimeRoot -Filter "ggml-cuda*.dll" -File -ErrorAction SilentlyContinue
    Get-ChildItem $runtimeRoot -Filter "cublas*.dll" -File -ErrorAction SilentlyContinue
)

$discoveredRelativePaths = @($cpuDlls + $optionalRuntimeFiles | ForEach-Object {
    "_internal\$($_.Name)"
})

$payloadRelativePaths = @(
    $requiredPayloadRelativePaths + $discoveredRelativePaths |
        Sort-Object -Unique
)

$manifestFiles = @()
$includeLines = @(
    "  { Generated by scripts\release\generate_bootstrap_payload.ps1 }"
)

foreach ($relativePath in $payloadRelativePaths) {
    $sourcePath = Join-Path $DistRoot $relativePath
    if (-not (Test-Path $sourcePath)) {
        throw "Missing bootstrap payload file: $sourcePath"
    }

    $sha256 = (Get-FileHash -Path $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
    $fileInfo = Get-Item $sourcePath
    $urlRelativePath = $relativePath -replace '\\', '/'
    $publicUrl = "$NormalizedBaseUrl/$urlRelativePath"

    $manifestFiles += [ordered]@{
        relative_path = $relativePath
        source_path = $sourcePath
        public_url = $publicUrl
        size_bytes = [int64]$fileInfo.Length
        sha256 = $sha256
    }

    $escapedRelativePath = $relativePath.Replace('\', '\\')
    $includeLines += "  AddPayloadFile('$escapedRelativePath', '$publicUrl', '$sha256');"
}

$manifest = [ordered]@{
    app = "Impulse"
    version = $Version
    generated_at_utc = (Get-Date).ToUniversalTime().ToString("o")
    base_url = $NormalizedBaseUrl
    files = $manifestFiles
}

$manifestPath = Join-Path $ProjectRoot "dist\Impulse-Bootstrap-Payload-$Version.json"
$manifest | ConvertTo-Json -Depth 5 | Set-Content -Path $manifestPath -Encoding UTF8
$includeLines | Set-Content -Path $IncludePath -Encoding ASCII

Write-Host "Bootstrap payload include written to $IncludePath"
Write-Host "Bootstrap payload manifest written to $manifestPath"
